[package]
name = "codegen-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
heck = "0.5.0"
prettyplease = "0.2.22"
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.76"
thiserror = "1.0.63"
toml = "0.8.19"
